version: '3'
services:
  flask-app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: flask_app
    volumes:
      - ./mysql-data:/var/lib/mysql

  redis:
    image: redis
    ports:
      - '6379:6379'
